name: Daily Commit Automation

on:
  schedule:
    - cron: '30 3 * * *'  # runs daily at 03:30 UTC
  workflow_dispatch:

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Commit for 24f2002824@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily-log.txt
          git config user.name "devsync-bot"
          git config user.email "24f2002824@ds.study.iitm.ac.in"
          git add daily-log.txt
          git commit -m "Automated update: $(date)" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
